### ISSUE TITLE
Docs: add known issues and solutions section to the docs

### ISSUE THREAD

**Issue by erezrokah** [decaporg/decap-website#11]
Related to https://github.com/netlify/netlify-cms/issues/2827

We should add a "known issues" section to the docs so users can self serve common issues.
Partial list to be updated:
- [ ] GitHub private+public+organisations permissions issues (e.g. https://github.com/netlify/netlify-cms/issues/1415)
- [ ] Having a branch named `cms` fails editorial workflow (https://github.com/netlify/netlify-cms/issues/3065)
- [ ] Working with multiple CMS instances/environments (e.g https://github.com/netlify/netlify-cms/issues/3790)
- [ ] Git gateway + Identity issues (e.g. https://github.com/netlify/netlify-cms/issues/3718 and https://community.netlify.com/t/common-issue-netlify-cms-git-gateway-email-not-confirmed/10690)
- [ ] Handling custom editor components in static site generators (https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/167)
Please add more in the comments if you have them

**Comment by privatemaker** [comment]
How relevant are these issues still? It seems most of them are closed.

**Comment by martinjagodic** [comment]
I just moved all issues tagged `area: docs` here without really assessing them. I agree that this is outdated and it would be better to focus on other things. Closing.
